### ISSUE TITLE
Voting links for most recent apps do not work

### ISSUE THREAD

**Issue by orestesgaolin** [hungrimind/flutter-of-the-year#70]
Some of the recently added apps have voting links like follows:

https://github.comundefined/

**Comment by tadaspetra** [comment]
ohp, it's a bug i found before. Your app name has a `:` in it and the regex screws up. Give me a few mins to fix

**Comment by tadaspetra** [comment]
Updated it to `-` instead and it's working now. I saw you have a website so I added the website to the page as well :)

Just to be clear, you only saw this issue on visible right, not other recently added apps?

> PS if you want it to be something other than `-` happy to change to that as long as it's not `:` because I don't want to mess with the regex in the GitHub Actions haha

**Comment by orestesgaolin** [comment]
Thanks, I remember seeing this with at least one other app, but now it's all good!
